include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_single_quotes
    - public_member_api_docs
    - require_trailing_commas
    - always_use_package_imports

msix_config:
  display_name: The Zurich Book
  publisher_display_name: ShadyTi
  identity_name: github.shadyti.zurich-book
  msix_version: 1.0.0.1
  logo_path: .\assets\appIcon.ico
